### ISSUE TITLE
Tesztek kódlefedettségének mérése

### ISSUE THREAD

**Issue by nyakaspeter** [BME-MIT-IET/EliteRoom-iet-2019#6]
Tesztek kódlefedettségének mérése JaCoCo eszközzel

**Comment by MrDouglas13** [comment]
[Wiki oldal](https://github.com/BME-MIT-IET/EliteRoom-iet-2019/wiki/2.1-Tesztek-k%C3%B3dlefedetts%C3%A9g%C3%A9nek-m%C3%A9r%C3%A9se)
